### ISSUE TITLE
Doesn't compile with DD4hep from master

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#738]
```
In file included from src/services/geometry/richgeo/ReadoutGeo.cc:6:
src/services/geometry/richgeo/ReadoutGeo.h:35:10: error: no type named 'long64' in namespace 'dd4hep'
        dd4hep::long64 cellID_dd4hep;
        ~~~~~~~~^
```

**Comment by wdconinc** [comment]
FYI https://github.com/AIDASoft/DD4hep/pull/1125 is in master, not in 1.25.1.

**Comment by wdconinc** [comment]
I don't like all these interface-breaking changes in DD4hep either (and I assume the next version will be 1.26). But in this case at least an `auto` may work in both 1.25.1 and master.

**Comment by c-dilks** [comment]
When do we plan to include https://github.com/AIDASoft/DD4hep/pull/1125 in our images?

`auto` won't help this `ReadoutGeo.h` case, but with 1125 we have [the new `CellID` type](https://github.com/MarkusFrankATcernch/DD4hep/blob/35dc496e2be17a55b3df7f1cc2ac6f821ca764fe/DDCore/include/DDSegmentation/BitFieldCoder.h#L26).

**Comment by c-dilks** [comment]
> Can you use `dd4hep::rec::DDSegmentation::CellID`? https://github.com/AIDASoft/DD4hep/blob/master/DDRec/include/DDRec/CellIDPositionConverter.h#L29

Yeah, looks like it; blame indicates this line is 6 years old.

**Comment by c-dilks** [comment]
> I'm hesitant to try to patch in a PR that touches so many source files since it inevitably requires a few other things to be patch in too. If we can avoid it, I'd prefer treating it without the patch.

@veprbl if `richgeo::ReadoutGeo` is not the only issue, can you post the other relevant errors?

**Comment by veprbl** [comment]
> > I'm hesitant to try to patch in a PR that touches so many source files since it inevitably requires a few other things to be patch in too. If we can avoid it, I'd prefer treating it without the patch.
> 
> @veprbl if `richgeo::ReadoutGeo` is not the only issue, can you post the other relevant errors?

Yes, at least according to `make --keep-going`.

**Comment by veprbl** [comment]
If common solution is not possible, we can always use `#if DD4HEP_VERSION_GE(1,26)`

**Comment by c-dilks** [comment]
> Yes, at least according to `make --keep-going`.

Any PID or RICH specific ones?

> If common solution is not possible, we can always use `#if DD4HEP_VERSION_GE(1,26)`

We should avoid this. If a change requires v1.26 or greater, then that should be the minimum version number EICrecon is compatible with.

**Comment by veprbl** [comment]
> > Yes, at least according to `make --keep-going`.
> 
> Any PID or RICH specific ones?

I missed the negation in your question. The issue presented here is the only issue seen.

> 
> > If common solution is not possible, we can always use `#if DD4HEP_VERSION_GE(1,26)`
> 
> We should avoid this. If a change requires v1.26 or greater, then that should be the minimum version number EICrecon is compatible with.

The upside of allowing wiggle room for compatibility is that you can easily run bisect on external dependencies to look for a bug. The downside is that you need to deprecate manually. Latter is a lesser evil IMO.

**Comment by veprbl** [comment]
And, more importantly, you can do comparisons of output for the same software to see if any regressions happen.
